#!/bin/bash

MENU="$(echo -e "Shutdown|Lock|Logout|Reboot" | rofi -sep "|" -dmenu -i -p 'System' -location 3 -xoffset -20 -yoffset 30 -width 10 -hide-scrollbar -line-padding 4 -padding 0 -lines 4)"
echo $MENU
case "$MENU" in
    Lock)       slock                   ;;
    Shutdown)   systemctl -i poweroff   ;;
    Logout)     bspc quit               ;;
    Reboot)     systemctl reboot        ;;
esac
