#! /bin/bash

bspc monitor -d {1..9}

bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 5
bspc config window_gap 10

# Borders and gaps
bspc config borderless_monocle true
bspc config gapless_monocle false

# Border colors
bspc config focused_border_color "#ffb300"
bspc config normal_border_color "#ffffff"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

# Focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config focus_by_distance true

# Misc
bspc config split_ratio 0.5
bspc config auto_alternate true
bspc config auto_cancel true
# bspc config initial_polarity first_child
# bspc config automatic_scheme spiral

# Rules
bspc rule -a Enpass             state=floating
bspc rule -a jetbrains-toolbox  state=floating
bspc rule -a mpv                state=floating
bspc rule -a feh                state=floating rectangle=800x600+560+240
bspc rule -a sxiv               state=floating center=true
bspc rule -a xfontsel           state=floating center=true focus=on
bspc rule -a lxappearance       state=floating center=true focus=on
bspc rule -a gimp               state=floating
bspc rule -a Steam              state=floating rectangle=800x600+560+240
bspc rule -a Godot              state=floating
bspc rule -a Godot_Engine       state=floating
bspc rule -a Godot_Editor       state=floating
bspc rule -a Godot_ProjectList  state=floating
bspc rule -a JDownloader        state=floating

xsetroot -cursor_name left_ptr
"$HOME/.config/polybar/launch.sh"

(pkill sxhkd; sxhkd) &
(pkill dunst; dunst) &
(pkill blueman-applet; blueman-applet) &
(pkill nm-applet; nm-applet) &
(pkill gnome-keyring; gnome-keyring) &
#(pkill barrier; barrier --restart) &
(pkill picom; sleep 2.0; picom) &

"$HOME/.local/bin/changewallpaper"

