#! /bin/bash

bspc monitor -d {1..9}

bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

# Borders and gaps
bspc config borderless_monocle true
bspc config gapless_monocle false

# Border colors
bspc config normal_border_color "#1F8999"
bspc config focused_border_color "#da123c"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

# Focusing behavior
bspc config focus_follows_pointer false
bspc config history_aware_focus false
bspc config focus_by_distance true

# Misc
bspc config split_ratio 0.5
bspc config auto_alternate true
bspc config auto_cancel true
# bspc config initial_polarity first_child
# bspc config automatic_scheme spiral

# Rules
bspc rule -a Firefox-esr -o desktop=^2 follow=on
bspc rule -a Enpass state=floating
bspc rule -a jetbrains-toolbox state=floating

bspc rule -a mpv state=floating

[[ ! $(pidof -x sxhkd) ]] && sxhkd &
[[ ! $(pidof -x compton) ]] && compton &
[[ ! $(pidof -x barrier) ]] && barrier --restart bismut.local &
nitrogen --set-zoom --random &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh
